---
silent: true
tasks:
  cleanse:
    cmds:
      - nix-collect-garbage --delete-old
  commit:
    cmds:
      - git add --all
      - git commit --all --message='changes'
      - git push
      - clear
  config:
    cmds:
      - sudo chown --recursive   --no-dereference x             ~/.config/Code\ -\ Insiders/User/
      - sudo chmod --recursive                    0755          ~/.config/Code\ -\ Insiders/User/
      - sudo chown --recursive   --no-dereference x             ~/.config/hypr/hyprland.conf
      - sudo chmod --recursive                    0755          ~/.config/hypr/hyprland.conf
      - sudo chown --recursive   --no-dereference x             ~/.config/hypr/shading.glsl
      - sudo chmod --recursive                    0755          ~/.config/hypr/shading.glsl
      - clear
  finder:
    cmds:
      - ls | grep "vscode-insiders" | grep -v '.drv$'
    dir: /nix/store/
  flake-a:
    cmds:
      - sudo nixos-rebuild switch -I nixos-config=/etc/nixos/configuration.nix {{.CLI_ARGS}}
  flake-c:
    cmds:
      - home-manager switch {{.CLI_ARGS}}
  flake-x:
    cmds:
      - task flake-a -- {{.CLI_ARGS}} --impure --flake .#x
  flake-z:
    cmds:
      - task flake-c -- {{.CLI_ARGS}} --impure --flake .#z@x
      - task config
      - clear
  format:
    cmds:
      - nix fmt **/*.nix
  repair:
    cmds:
      - sudo nix-store --verify --repair --check-contents
  repair-boot:
    cmds:
      - sudo nixos-rebuild boot --impure
  sh-512:
    cmds:
      - mkpasswd --method=sha-512 --salt=HarayKrsna
  update:
    cmds:
      - sudo nix flake update --extra-experimental-features flakes --extra-experimental-features nix-command
version: '3'
